### ISSUE TITLE
Computing total slashed tokens for a validator

### ISSUE THREAD

**Issue by brentstone** [informalsystems/partnership-heliax#49] opened 2023-05-03 22:26 UTC
The Namada design calls for slashed tokens to be transferred to an address called the "Slash Pool." Governance can do one of two things with these slashed tokens:
1. burn them
2. refund the slashed accounts in case the slash is deemed accidental after the fact

This behavior is currently not addressed in the model. The possibility of multiple slashes in neighboring epochs for a single validator in Namada also likely complicates the desired procedure.

We would like to draw up pseudocode for this behavior and include it in the model if possible.

**Comment by angbrav** [comment] 2023-05-10 14:39
> The possibility of multiple slashes in neighboring epochs for a single validator in Namada also likely complicates the desired procedure.

Extending this bit before I forget. The problem is that when a validator misbehaves multiple times within an epoch window of less than `unbonding_length` epochs, then we may not be able to slash the precise amount because the validator may run out of stake. This is because the validator in those cases is misbehaving multiple times with the same tokens. Then, we need to be careful what we move to the `slash_pool` and move exactly what we were able to take from the validator's stake.

**Comment by angbrav** [comment] 2023-12-21 15:15
Agreed to close it.

**Closed as completed by angbrav** 2023-12-21 15:15 UTC
Labels: enhancement
